/**
 * Game State Factory
 *
 * Produces a blank GameState. The engine's initGame / hydrateGameState methods
 * set meaningful values; this factory just provides safe defaults so every
 * field is always defined.
 */

import type { GameState } from './types';
import { createRng } from './rng';
import { createInitialHeroMagicState } from '@/lib/heroMagic';
import {
  INITIAL_HP,
  INITIAL_GOLD,
  INITIAL_TURN_COUNT,
  INITIAL_PERSUADE_LEVEL,
  INITIAL_STUN_CAP,
  createEmptySlotBonusState,
  createEmptyEquipmentBuffState,
  createEmptyActiveRow,
  initialCombatState,
} from './constants';

export function createInitialGameState(): GameState {
  return {
    hp: INITIAL_HP,
    gold: INITIAL_GOLD,
    turnCount: INITIAL_TURN_COUNT,
    shopLevel: 0,
    monstersDefeated: 0,
    totalDamageTaken: 0,
    totalHealed: 0,
    healAccumulator: 0,
    turnDamageTaken: 0,
    cardsPlayed: 0,
    recycleForgePlayCount: 0,
    classDamageDiscoverStreak: 0,
    classMagicDiscoverStreak: 0,
    waveDiscardCount: 0,
    totalWins: 0,
    undoCount: 0,

    previewCards: createEmptyActiveRow(),
    activeCards: createEmptyActiveRow(),
    previewCardStacks: {},
    activeCardStacks: {},
    waterfallDealBonus: 0,
    pendingWaterfallPlan: null,
    remainingDeck: [],
    discardedCards: [],
    handCards: [],

    equipmentSlot1: null,
    equipmentSlot2: null,
    equipmentSlot1Reserve: [],
    equipmentSlot2Reserve: [],
    equipmentSlotCapacity: { equipmentSlot1: 1, equipmentSlot2: 1 },
    equipmentSlotBonuses: createEmptySlotBonusState(),
    amuletSlots: [],
    maxAmuletSlots: 2,

    backpackItems: [],
    permanentMagicRecycleBag: [],
    backpackCapacityModifier: 0,
    classDeck: [],
    classCardsInHand: [],

    heroVariant: { id: '', name: '', classTitle: '', image: '' },
    heroClass: '',
    selectedHeroSkill: null,
    extraHeroSkills: [],
    extraSkillsUsedThisWave: [],
    permanentSkills: [],
    permanentMaxHpBonus: 0,
    permanentSpellDamageBonus: 0,
    permanentSpellLifesteal: 0,
    stunCap: INITIAL_STUN_CAP,
    heroStunned: false,
    monsterKillUpgradeProgress: 0,
    recycleBackpackProgress: 0,
    swapUpgradeProgress: 0,
    flipOverkillLifestealProgress: 0,
    equipAmuletCapProgress: 0,
    stunAttemptDiscoverProgress: 0,
    flipDebuffMonsterId: null,
    bugletAmuletObtained: false,
    statSwapCardObtained: false,
    handLimitBonus: 0,
    heroMagicState: createInitialHeroMagicState(),
    wraithPassiveEnabled: false,
    persuadeLevel: INITIAL_PERSUADE_LEVEL,
    persuadeCostModifier: 0,
    lastPersuadeTargetId: null,
    consecutivePersuadeCount: 0,
    persuadeSameTargetCostHalve: false,
    persuadeRaceBonus: {},
    persuadeSuccessDurabilityBonus: 0,
    persuadeAmuletBonus: 0,
    permanentPersuadeBonus: 0,
    persuadeDiscount: null,
    lastPlayedCardCategory: null,
    transformChainPrevCategory: null,
    consecutiveTransformStreak: 0,
    magicCardsPlayedThisTurn: 0,
    damageMagicPlayedThisTurn: 0,

    combatState: { ...initialCombatState },
    tempShield: 0,

    nextWeaponBonus: 0,
    nextShieldBonus: 0,
    weaponMasterBonus: 0,
    shieldMasterBonus: 0,
    vampiricNextAttack: false,
    unbreakableNext: false,
    unbreakableUntilWaterfall: {},
    bulwarkPassiveActive: 0,
    bulwarkTempArmorStacks: 0,
    slotTempArmor: { equipmentSlot1: 0, equipmentSlot2: 0 },
    slotTempAttack: { equipmentSlot1: 0, equipmentSlot2: 0 },
    amuletAuraAppliedThisWave: false,
    defensiveStanceActive: false,
    slotAttackBursts: createEmptyEquipmentBuffState(),
    nextAttackLifestealSlot: null,
    berserkTurnBuff: createEmptyEquipmentBuffState(),
    extraAttackCharges: 0,
    slotExtraAttacks: { equipmentSlot1: 0, equipmentSlot2: 0 },
    doubleNextMagic: false,
    heroSkillUsedThisWave: false,
    berserkerRageActive: false,
    berserkerSlotUsed: {},
    flashSlotUsed: {},
    gambitExtraActive: false,
    gambitExtraPerSlot: 1,
    gambitSlotUsed: {},
    weaponExtraAttackUsed: {},
    blockDurabilityPerSlot: 1,
    slotBattleSpiritBonus: {},
    slotBattleSpiritUsed: {},

    pendingHeroSkillAction: null,
    pendingHeroMagicAction: null,
    pendingMagicAction: null,
    pendingHandDiscardSelection: null,
    pendingPotionAction: null,
    deathWardPrompt: null,
    pendingMonsterEndDiceQueue: [],

    monsterRewardQueue: [],
    activeMonsterReward: null,
    selectedMonsterRewards: null,
    monsterRewardPreviewCache: {},

    shopOfferings: [],
    shopSourceEvent: null,
    shopDeleteUsed: false,
    shopHealUsed: false,
    shopLevelUpUsed: false,
    shopSkillDiscoverUsed: false,
    shopEquipAttackUsed: false,
    shopEquipArmorUsed: false,
    shopSkillOptions: [],

    currentEventCard: null,
    resolvingDungeonCardId: null,
    pendingEventEffects: [],
    pendingEventSkipFlip: false,
    eventModalOpen: false,
    eventModalMinimized: false,
    eventDiceModal: null,
    eventTransformState: null,
    persuadeState: null,
    magicChoiceModal: null,

    discoverModalOpen: false,
    discoverOptions: [],
    discoverSourceLabel: null,
    pendingClassDiscoverQueue: [],
    deleteModalOpen: false,
    upgradeModalOpen: false,
    upgradeModalMaxCount: undefined,
    handMagicUpgradeModal: null,
    mirrorCopyModal: null,
    permGrantModal: null,
    amplifyModal: null,
    eventAmplifyHandPicker: null,
    graveyardDiscoverState: null,
    graveyardDiscoverDelivery: 'backpack',
    cardActionContext: null,
    equipmentPrompt: null,
    ghostBladeExileCards: null,

    shopModalOpen: false,
    shopModalMinimized: false,
    shopSkillSelectOpen: false,

    gameMode: 'normal',
    gameOver: false,
    victory: false,
    showSkillSelection: false,
    showCardDraft: false,
    cardDraftPool: [],
    drawPending: false,
    isHydrated: false,
    heroSkillBanner: null,

    eternalRelics: [],
    classCardPreviewId: null,

    gameLogEntries: [],

    honorSweepUpgradesPending: 0,

    amplifiedCardBonus: {},

    processedDungeonCardIds: [],
    pendingAutoDrawCount: 0,

    actionQueue: [],
    phase: 'idle',
    actionLog: [],

    rng: createRng(Date.now()),
    lastFlowDiceRoll: null,
  };
}
